FROM	debian:latest

RUN apt update && apt upgrade -y
RUN apt install nginx vim openssl -y 
RUN sed -i 's/ssl_protocols TLSv1 TLSv1.1 TLSv1.2;/ssl_protocols TLSv1.2;/g' /etc/nginx/nginx.conf
COPY default /etc/nginx/sites-available/
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj "/C=MA/ST=SRAGHNA /L=Benguerir /O=1337/OU=Cluster/CN=localhost/emailAddress=mbifenzi@student.1337.ma"
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]