version: '3'

services:
    mariadb:
        build: ./requierements/mariadb 
        image: db
        container_name : db
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - .env
        networks:
            - wordpress
        # volumes:
        #     - /home/mbifenzi/Desktop/1337/inception/srcs/volumes:/var/lib/mysql
    nginx:
        build: ./requierements/nginx
        depends_on:
            - wordpress
        image: ng
        container_name : ng
        restart: unless-stopped
        ports:
            - "443:443"
        networks:
            - wordpress
        volumes:
            - 'wordpress:/var/www/html/'
    wordpress:
        build: ./requierements/wordpress
        image: wp
        depends_on:
            - mariadb
        container_name : wp
        restart: unless-stopped
        ports:
            - "9000:9000"
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - 'wordpress:/var/www/html/'
networks:
  wordpress:
    driver: bridge


volumes:
    wordpress:
        driver_opts:
            o: bind
            type: ext4
            device: /Users/mbifenzi/volume/wp
