version: '3'

services:
    mariadb:
        build: ./srcs/mariadb 
        image: mymariadb
        container_name : mymariadb
        # restart: unless-stopped
        # ports:
        #     - "3306:3306"
        env_file:
            - .env
        networks:
            - wordpress
        # volumes:
        #     - /Users/mbifenzi/Desktop/1337/inception/srcs/volumes:/var/lib/mysql
    # nginx:
    #     build: ./srcs/nginx
    #     image: mynginx
    #     container_name : mynginx
    #     restart: unless-stopped
    #     ports:
    #         - 443:443
    #     networks:
    #         - wordpress
    # wordpress:
    #     build: ./srcs/mariadb
    #     image: mymariadb
    #     depends_on:
    #         - mariadb
    #     container_name : mymariadb
    #     restart: unless-stopped
    #     ports:
    #         - "9000"
    #     network:
    #         - wordpress
networks:
  wordpress:
    driver: bridge