FROM	debian:buster

RUN apt update && apt upgrade -y
RUN apt install mariadb-server -y
COPY ./tools/mariadb.sh /
COPY ./conf/wordpress.sql /
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
EXPOSE 3306
CMD ["sh", "mariadb.sh"]
