FROM	debian:buster

RUN apt update && apt upgrade -y
RUN apt install mariadb-server -y
# RUN chown -R mysql: /var/lib/mysql
RUN sleep 10
# RUN 
COPY ./conf/script.sh /
COPY ./conf/final.sql /
COPY ./conf/my.cnf /etc/mysql/
RUN chmod +x script.sh
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
EXPOSE 3306
CMD ["sh", "script.sh"]
