FROM	debian:buster

RUN apt update
RUN apt install mariadb-server -y
# RUN chown -R mysql: /var/lib/mysql§§
# RUN sleep 10
# RUN 
COPY ./script.sh /
COPY my.cnf /etc/mysql/
RUN chmod +x script.sh
RUN chmod +x /etc/mysql/my.cnf
EXPOSE 3306
CMD ["sh", "script.sh"]
