FROM	debian:buster

RUN apt update
RUN apt install mariadb-server -y
# RUN chown -R mysql: /var/lib/mysql
# RUN sleep 10
# RUN 
COPY ./script.sh /
RUN chmod +x script.sh
EXPOSE 3306

# ENTRYPOINT sleep infinity

ENTRYPOINT  mysqld_safe \
            && mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${USER_PASSWORD}';" \
            && mysql -u root -p${USER_PASSWORD} -e "FLUSH PRIVILEGES;" \
            && mysql -u root -p${USER_PASSWORD} -e "use mysql; update user set user='${USER}' where user='root';" \
            && mysql -u root -p${USER_PASSWORD} -e "FLUSH PRIVILEGES;" \
           ; sleep infinity

# CMD ["sh", "script.sh"]
