FROM	debian:buster

RUN apt update && apt upgrade -y
RUN apt install nginx vim openssl -y 
RUN sed -i 's/ssl_protocols TLSv1 TLSv1.1 TLSv1.2;/ssl_protocols TLSv1.2;/g' nginx.conf
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/C=MA/ST=SRAGHNA /L=Benguerir /O=1337/OU=Cluster/CN=localhost/emailAddress=mbifenzi@student.1337.ma"
