FROM debian:buster
RUN apt-get update 
RUN apt install -y curl
RUN apt update
RUN apt install -y php-fpm php-mysql
RUN cd /tmp \
    && curl -LO https://wordpress.org/latest.tar.gz && tar xzvf latest.tar.gz \
    && mkdir -p /var/www/html \
    && cp -r /tmp/wordpress/* /var/www/html/ \
    && chown -R www-data:www-data /var/www/html/
RUN sed -i 's|listen = /run/php/php7.3-fpm.sock|listen = 0.0.0.0:9000|g' /etc/php/7.3/fpm/pool.d/www.conf
RUN mkdir run/php/
COPY wp-config.php ./var/www/html/
ENTRYPOINT php-fpm7.3 -F -R